spring:  
  profiles:
    active:
      - dev
---
spring:
  profiles:
    application:
      name: miscroservicecloud-config-atguigu-dev
---
spring:
  profiles:
    application:
      name: miscroservicecloud-config-atguigu-test
#请保存为UTF-8格式